### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by amanuel1995** [amanuel1995/MI-449-SS17-741-css-frameworks-p1twXJ#1]
@KatieMFritz Can you take a look at this? It's [hosted here](https://amanuel1995.github.io/MI-449-SS17-741-css-frameworks-p1twXJ/) and meets the following criteria:

- [x] Include the CSS and JS for Bootstrap 3 (not 4) in the page (including the "jQuery" dependency)
- [x] Use the `container` class to center your page content
- [x] Use a `navbar` class to display the name of your site and a list of at least 3 links (to past projects, or anything else) at the top of your page
- [x] Split your main content into 2 columns on large (`lg`) and medium (`md`) sized screens, but collapse them on top of each other on small (`sm`) and extra small (`xs`) screens
- [x] Use a `thumbnail` class on an at least one image in your page

**Comment by KatieMFritz** [comment]
Great start, Amanuel! 😄 Your page does technically meet all the project criteria. However, I'm going to push you a bit so you know how to write even better code in the future.

### Reference to missing file

**In your `head`, you have  `<link rel="stylesheet" href="/css/master.css">`, but there's no `master.css` in this project.** If I were you, I'd just remove the `link` rather than add the stylesheet. 😆 

### Dependencies must be referenced first

When I checked the javascript console for your site (don't worry about what that is yet - it's a tool we'll be learning soon), I saw an error that Bootstrap requires jQuery. You *did* include jQuery, but you included it after the Bootstrap `js` file. **CSS and JS files need to be referenced in a certain order, with the dependency files (like jquery) listed before the files that use them (like Bootstrap).** 

### JavaScript goes at the end of the `body` element

While there's [some debate over this](http://stackoverflow.com/questions/436411/where-is-the-best-place-to-put-script-tags-in-html-markup), **the traditional place for all `script` links and `script` elements is at the very end of the code, right before `</body>`**. If you're curious about why, talk to Chris on Slack. :smile:

### Bootstrap Navbar

Looks awesome! 👍 

I noticed that your site name/brand name links to `index.html`, which is a relative link. Have you done the lesson on [multi page websites](https://msu.lansing.codes/courses/MI-449-SS17-741/lessons/html-multiple-pages/1) yet? When you do, you'll learn a little more about types of links and when to use them. **For a home page link, I would definitely use `/` instead of `index.html`.** 

### Bootstrap Columns

While specifying column classes for every screen width (`<div class="col-md-6 col-lg-6 col-xs-12 col-s-12">`) isn't *invalid*, it's unnecessary. 

From the [Bootstrap 3 Docs > Grid System](http://getbootstrap.com/css/#grid):

> Grid classes apply to devices with screen widths **greater than or equal to the breakpoint sizes**, and **override grid classes targeted at smaller devices**. Therefore, e.g. applying any .col-md-* class to an element will not only affect its styling on medium devices but also on large devices if a .col-lg-* class is not present.

By default, if you don't specify a `col` class, the column will be full width. So for this assignment, you can just use `.col-md-6` to say that you want the div to span 12 columns on screen sizes *smaller* than medium, and 6 columns on screen sizes medium and larger. 

The fourth row in [this Bootstrap example](http://getbootstrap.com/css/#grid-example-basic) shows the behavior you want to create.

This grid stuff can be confusing - it takes practice! Study the Bootstrap docs, play around with your code, and let me know if you have questions. 

PS Nice comments! Comments definitely help you keep track of what's happening in complex grid systems. 💯

**Comment by amanuel1995** [comment]
Hey @KatieMFritz, as always thanks for your detailed explanations and comments. I did front-end Web Dev and that's why am lazy doing most of the front-end stuff. Just too excited for the backend stuff. But I am learning a lot that I didn't pay attention to last semester.

I think I did complete it now. Look at it and let me know.

**Comment by KatieMFritz** [comment]
First off, excellent commit message, once again!

Second: you flatter me. 😊 I'm really glad you find the comments helpful. 

Third: This looks AWESOME. :shipit:
